#!/usr/bin/env bash
#SBATCH --job-name=insilico_run_dynGENIE3_20genes_3degree
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=1G
#SBATCH -o %A_%a.out    # stdout
#SBATCH -e %A_%a.err    # stderr
#SBATCH --array=0-9

STEP=10
INSTANCES=$((STEP*10))
GENES=20
DEGREE=3

FIRST=$((SLURM_ARRAY_TASK_ID * STEP + 1))
END=$((FIRST + STEP - 1))

module load conda
conda activate /NetScratch/REGARN/GRN/conda_GRN

python dynGENIE3_100insilico_networks.py $FIRST $END $GENES $DEGREE